// swift-tools-version: 6.0
import Foundation
import PackageDescription

// Where scripts/build-ffi.sh stages the dylib. Derived from #filePath rather than written as a
// relative path: the linker's working directory is not guaranteed to be the package root, and a
// relative -L that resolves somewhere else fails as "library not found" with no hint why.
let packageDirectory = URL(fileURLWithPath: #filePath).deletingLastPathComponent().path
let ffiLibraryDirectory = packageDirectory + "/.ffi/lib"

let package = Package(
    name: "MacDaemon",
    // Testing.framework is built for macOS 14; ScreenCaptureKit's SCStream needs 13+.
    platforms: [.macOS(.v14)],
    targets: [
        // The C half of the UniFFI bindings. The name is not ours to choose: the generated
        // text_policy_ffi.swift contains a literal `import text_policy_ffiFFI`, so the module —
        // and therefore the SwiftPM target — has to be called exactly that. Both this directory's
        // contents and .ffi/lib are generated by scripts/build-ffi.sh and gitignored; a fresh
        // checkout must run that script before anything here will build.
        .systemLibrary(name: "text_policy_ffiFFI"),
        .target(
            name: "TextPolicyFFI",
            dependencies: ["text_policy_ffiFFI"],
            // These belong here, not on the executable target, because they have to reach the test
            // bundle too — and `unsafeFlags` on a test target makes SwiftPM silently run zero
            // tests. Linker settings on a dependency propagate to every product that links it,
            // which gets the rpath into MacDaemonPackageTests.xctest without touching that target.
            linkerSettings: [
                .unsafeFlags([
                    "-L\(ffiLibraryDirectory)",
                    // The dylib's install name is @rpath/libtext_policy_ffi.dylib, so something
                    // has to supply the rpath. @executable_path/../Frameworks is the shipping
                    // case; the absolute build-tree path covers `swift test` and a binary run
                    // straight out of .build, neither of which is inside an .app.
                    //
                    // DYLD_LIBRARY_PATH is not an alternative: `swift test` execs Apple's signed
                    // swiftpm-testing-helper, and SIP strips DYLD_* across that exec, so the
                    // variable never reaches the process that loads the bundle.
                    "-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks",
                    "-Xlinker", "-rpath", "-Xlinker", ffiLibraryDirectory,
                ]),
                .linkedLibrary("text_policy_ffi"),
            ]),
        .target(name: "MacDaemon", dependencies: ["TextPolicyFFI"]),
        .executableTarget(name: "holy-blocker-macd", dependencies: ["MacDaemon"]),
        // Do not add `unsafeFlags` to this target. SwiftPM silently stops discovering and running
        // tests when a test target carries them — `swift test` builds, prints nothing, and exits
        // 0. The Command Line Tools paths swift-testing needs, and the DYLD_LIBRARY_PATH the test
        // bundle needs to find libtext_policy_ffi.dylib, are passed by scripts/test.sh.
        .testTarget(name: "MacDaemonTests", dependencies: ["MacDaemon", "TextPolicyFFI"]),
    ]
)
